### ISSUE TITLE
how to have a executable in cpp-cheat/shared_library/basic/

### ISSUE THREAD

**Issue by behnamben** [cirosantilli/cpp-cheat#13]
I tried to change the make file but it doesn't work. I want to have an executable instead of a library file.

**Comment by cirosantilli** [comment]
I don't understand, why do you expect to get an executable from the shared_library directory, which is basically one of the only directories in this project that generates libraries and not executables?

**Comment by behnamben** [comment]
Since it was a c training, I was trying to make an executable that uses dlopen inside itself.

**Comment by cirosantilli** [comment]
OK. Didn't https://github.com/cirosantilli/cpp-cheat/blob/master/shared_library/basic/dlopen.c work? Just worked for me. Gotta run as:

```
LD_LIBRARY_PATH=`pwd` ./dlopen.out
```
