### ISSUE TITLE
Interested in a value category cheatsheet link?

### ISSUE THREAD

**Issue by jeaye** [cirosantilli/cpp-cheat#2]
I have developed https://github.com/jeaye/value-category-cheatsheet/blob/master/value-category-cheatsheet.pdf and it may fit into this repo well.

**Comment by cirosantilli** [comment]
I don't want no stinking PDF!

I want this: https://github.com/jeaye/value-category-cheatsheet/tree/master/resources/code

https://github.com/cirosantilli/cpp-cheat/commit/38f5609cd76ab95a1835a92f42b65590bdbb0261

:-)

**Comment by jeaye** [comment]
:)

**Comment by jeaye** [comment]
Oh, on second glance, I think that link should be to master, not a specific commit. The one you linked here, in the comment, is to master, but the one you committed is to a specific commit: 14aef17fb5ab9c35416ec62ac0d45eb12729901f

**Comment by cirosantilli** [comment]
Yeah, it is intentional. If you ever move the directory, the link survives, just like a git submodule ;-)

**Comment by jeaye** [comment]
Okie dokie. Thanks!
